all:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/src\plugins\qmltooling\qmldbg_ost\qmldbg_ost.pro  -o Makefile -spec win32-msvc2008
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/src\plugins\qmltooling\qmldbg_ost\qmldbg_ost.pro  -o Makefile -spec win32-msvc2008
