all:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/config.tests\unix\openssl\openssl.pro  -o Makefile -spec win32-msvc2008
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/config.tests\unix\openssl\openssl.pro  -o Makefile -spec win32-msvc2008
