all:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/tools\qdbus\qdbusxml2cpp\qdbusxml2cpp.pro  -o Makefile -spec win32-msvc2008
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/tools\qdbus\qdbusxml2cpp\qdbusxml2cpp.pro  -o Makefile -spec win32-msvc2008
