all:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/tools\macdeployqt\macchangeqt\macchangeqt.pro  -o Makefile -spec win32-msvc2008
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/tools\macdeployqt\macchangeqt\macchangeqt.pro  -o Makefile -spec win32-msvc2008
