all:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/src\s60installs\s60installs.pro  -o Makefile -spec win32-msvc2008
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/src\s60installs\s60installs.pro  -o Makefile -spec win32-msvc2008
