all:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/doc\src\snippets\qlistwidget-using\qlistwidget-using.pro  -o Makefile -spec win32-msvc2008
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\Qt\Qt4.8.6\bin\qmake C:/Qt/Qt4.8.6/doc\src\snippets\qlistwidget-using\qlistwidget-using.pro  -o Makefile -spec win32-msvc2008
